[Window]
fullscreen = true
width = 800
height = 600

[Appearance]
font = Open Sans
font_size = 14
label_size = 14
background = #2e2e2e
foreground = #ffffff
selection = #b4b4b4
opacity = 0.85

[Grid]
columns = 4
